# Site settings
title: CK_Daniel
description: A personal site of CK_Daniel
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: CK_Daniel
user_description: My name is Daniel! A computer science student that is graduating in 2 months. 
user_title: Software Developer
email: daniel2005315@gmail.com
#twitter_username: lorem_ipsum
github_username:  CK_Daniel
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
